# Generated by Django 3.0.3 on 2020-02-15 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_auto_20200215_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
